version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
    - "gunicorn"
    - "misite.wsgi:application"
    - "--bind"
    - "0.0.0.0:8000"
    ports:
      - '8000:8080'
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max_file: "10"
        max_size: "200k"
    volumes:
      - ./misite/database:/app/database
