# Generated by Django 4.2.16 on 2024-11-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
