# Generated by Django 4.2.16 on 2024-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
