# Generated by Django 4.2.16 on 2024-11-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_product_created_by_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
