# Generated by Django 4.2.16 on 2024-11-19 11:48

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=myauth.models.create_path_to_upload_images),
        ),
    ]
